import Head from 'next/head'
import styles from '../styles/Home.module.css'
import About from './about'
import { Adhyayan, Pooja } from './components/Poojan'
import Contact from './contact'

export default function Home() {
  return (
    <div className={`bg-gray`}>
      <div>
        <Head>
          <title>Karmakaand</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className='container-fluid' style={{ padding: "90px" }}>
          <h1 className={styles.title}>
            Karmakaand
            {/* <a href="https://nextjs.org">Next.js!</a> */}
          </h1>

          <p className={styles.description}>
            Poojan va Adhyayan kare saralta se
          </p>
          <div style={{ display: "flex", flexWrap: "wrap", justifyContent: "center" }}>
            <a href='/poojan'><button type="submit" style={{ margin: "10px" }} className="button-cool sm-w-full">Poojan</button></a>
            <a href='/adhyayan'><button type="submit" style={{ margin: "10px" }} className="button-cool sm-w-full">Adhyayan</button></a>
          </div>
        </main>
        <div className="bg-white" style={{ padding: "50px 0" }}>
          <div className='container-fluid'>
            <Pooja />
            <Adhyayan />
          </div>
        </div>
        <About className='bg-gray' />
        <Contact />
      </div>
    </div>
  )
}
